# Generated by Django 3.2.9 on 2022-01-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220117_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='url_social_page',
            field=models.TextField(blank=True, verbose_name='ссылка на социальную сеть'),
        ),
    ]
